### ISSUE TITLE
error when using google scraper

### ISSUE THREAD

**Issue by iphqne** [d4n3436/GScraper#1]
code is here:
                           GoogleScraper GoogleScraper = new GoogleScraper();
                            IEnumerable<IImageResult> images = await GoogleScraper.GetImagesAsync(query);
                            Random Random = new Random();
                            int image = Random.Next(0, images.Count());
                            message.Channel.SendMessage(images.ElementAt(image).Url);

i get this error:
GScraper.GScraperException: Failed to unpack the image object data.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
   at System.String.IndexOf(Char value, Int32 startIndex, Int32 count)
   at System.String.IndexOf(Char value, Int32 startIndex)
   at GScraper.Google.GoogleScraper.ExtractDataPack(String page)
   at GScraper.Google.GoogleScraper.GetImagesAsync(String query, SafeSearchLevel safeSearch, GoogleImageSize size, String color, GoogleImageType type, GoogleImageTime time, String license, String language)
   --- End of inner exception stack trace ---
   at GScraper.Google.GoogleScraper.GetImagesAsync(String query, SafeSearchLevel safeSearch, GoogleImageSize size, String color, GoogleImageType type, GoogleImageTime time, String license, String language)
   at Ascension.♠.♫.MoveNext()

if i use duckduckgoscraper this doesn't happen but duckduckgo returns irrelevant images quite a lot so i'd prefer if google worked

**Comment by d4n3436** [comment]
Hello, could you provide the search query you used so I can replicate the bug?

**Comment by iphqne** [comment]
happens with any search query i try
this is a discord bot
var query = content.Replace($"{prefix}image ", "");
string content = MessageEventArgs.Message.Content.ToString().ToLower();

**Comment by d4n3436** [comment]
The exception you're getting is produced when the library can't extract the image data from the downloaded page. You may have triggered a CAPTCHA on the Google Search page, producing the exception.
Could you try opening/downloading this URL (https://www.google.com/search?q=google&tbm=isch) and see if a CAPTCHA has been triggered?
If not, please upload the HTML file here so I can replicate the bug and make a fix.

**Comment by iphqne** [comment]
no captcha, here is the html file
[google.zip](https://github.com/d4n3436/GScraper/files/9228208/google.zip)

**Comment by d4n3436** [comment]
I tested the HTML file and it's extracting the images without problems. Are you using the latest version of GScraper? If not, please update it. Also, make sure you're obtaining the file from the same system you're getting the exception from.

**Comment by iphqne** [comment]
yes, i'm on the latest version. i downloaded the source and built it myself to make sure. when it gets called i get this error
![image](https://user-images.githubusercontent.com/45533114/182015474-a2658b8e-5a2a-450c-a850-a00751dd7386.png)
This exception was originally thrown at this call stack:
    [External Code]
    GScraper.Google.GoogleScraper.ExtractDataPack(string) in GoogleScraper.cs
    GScraper.Google.GoogleScraper.GetImagesAsync(string, GScraper.SafeSearchLevel, GScraper.Google.GoogleImageSize, string, GScraper.Google.GoogleImageType, GScraper.Google.GoogleImageTime, string, string) in GoogleScraper.cs

on this line:
IEnumerable<IImageResult> images = await GoogleScraper.GetImagesAsync(query);

![image](https://user-images.githubusercontent.com/45533114/182015485-cd8ea400-2d67-436c-ad38-bde287adcb71.png)

Unhandled exception. GScraper.GScraperException: Failed to unpack the image object data.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
   at System.String.IndexOf(Char value, Int32 startIndex, Int32 count)
   at System.String.IndexOf(Char value, Int32 startIndex)
   at GScraper.Google.GoogleScraper.ExtractDataPack(String page) in C:\Users\Cameron\Desktop\GScraper-master\src\GScraper\Google\GoogleScraper.cs:line 117
   at GScraper.Google.GoogleScraper.GetImagesAsync(String query, SafeSearchLevel safeSearch, GoogleImageSize size, String color, GoogleImageType type, GoogleImageTime time, String license, String language) in C:\Users\Cameron\Desktop\GScraper-master\src\GScraper\Google\GoogleScraper.cs:line 80
   --- End of inner exception stack trace ---
   at GScraper.Google.GoogleScraper.GetImagesAsync(String query, SafeSearchLevel safeSearch, GoogleImageSize size, String color, GoogleImageType type, GoogleImageTime time, String license, String language) in C:\Users\Cameron\Desktop\GScraper-master\src\GScraper\Google\GoogleScraper.cs:line 84
   at Ascension.Program.DiscordSocketClient_OnMessageReceived(DiscordSocketClient DiscordSocketClient, MessageEventArgs MessageEventArgs) in C:\Users\Cameron\Desktop\i\Ascension\Ascension\Ascension\Program.cs:line 2564
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback() - error with line info

**Comment by d4n3436** [comment]
I'm not really sure what's causing the exception. Can you try using the example program?

**Comment by iphqne** [comment]
GScraper Example Program
Query (enter 'e' to exit): test
GScraper.GScraperException: Failed to unpack the image object data.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')
   at System.String.IndexOf(Char value, Int32 startIndex, Int32 count)
   at System.String.IndexOf(Char value, Int32 startIndex)
   at GScraper.Google.GoogleScraper.ExtractDataPack(String page) in C:\Users\Cameron\Desktop\GScraper-master\src\GScraper\Google\GoogleScraper.cs:line 117
   at GScraper.Google.GoogleScraper.GetImagesAsync(String query, SafeSearchLevel safeSearch, GoogleImageSize size, String color, GoogleImageType type, GoogleImageTime time, String license, String language) in C:\Users\Cameron\Desktop\GScraper-master\src\GScraper\Google\GoogleScraper.cs:line 80
   --- End of inner exception stack trace ---
   at GScraper.Google.GoogleScraper.GetImagesAsync(String query, SafeSearchLevel safeSearch, GoogleImageSize size, String color, GoogleImageType type, GoogleImageTime time, String license, String language) in C:\Users\Cameron\Desktop\GScraper-master\src\GScraper\Google\GoogleScraper.cs:line 84
   at GScraperExample.Program.Main() in C:\Users\Cameron\Desktop\GScraper-master\examples\GScraperExample\Program.cs:line 35

![image](https://user-images.githubusercontent.com/45533114/182015985-913d78f0-2295-4644-88f6-ee87c0752cd4.png)

**Comment by d4n3436** [comment]
Ok, you're getting the exception on example program which is good. Now open `GoogleScraper.cs` (on folder Google), go to line 75 and add below the following line: `System.IO.File.WriteAllText("path to file.html", page);`

It should look like this:
![image](https://user-images.githubusercontent.com/39978852/182016115-5610b76d-9b44-4811-aa1f-e8d9dcd40539.png)

Run the program until you get the exception, then upload the file here.

**Comment by iphqne** [comment]
![image](https://user-images.githubusercontent.com/45533114/182016311-7269e663-2a75-4fe3-aa48-8c55802755f8.png)
[test.zip](https://github.com/d4n3436/GScraper/files/9228275/test.zip)

going to head to sleep now so if this isn't enough to solve it and you still need more i'll do it when i wake up, thank you for the help

**Comment by iphqne** [comment]
ah well, this makes sense as to why it's happening
![image](https://user-images.githubusercontent.com/45533114/182016458-e2c5de09-f235-43dd-8ad9-fc47ce4b0858.png)

**Comment by d4n3436** [comment]
Oh I see, that's why the error only occurred from inside the program. I'll have to do some research on how to bypass the cookie consent page. It didn't affect the library before because it was only a pop-up but now it's a separate page.

A temporary workaround would be to get the cookie from your browser and use it on the `HttpClient` parameter of the `GoogleScraper` constructor.

**Comment by iphqne** [comment]
if you haven't pushed the fix yet when i wake up i'll do that temporary fix until you come up with a better solution, thank you

**Comment by d4n3436** [comment]
I've pushed a commit that should fix the error. If you're still having problems feel free to reopen this issue.

**Comment by iphqne** [comment]
works now, thank you. just wondering how to enable safe search on googlescraper though

**Comment by d4n3436** [comment]
Use the 2nd parameter of `GetImagesAsync`.
